using SqlSchemaCompare.Core.Interfaces; using SqlSchemaCompare.Core.Models;
namespace SqlSchemaCompare.Core.Comparers;
public sealed class SchemaComparer : ISchemaComparer
{
    public IReadOnlyList<SchemaDifference> Compare(DatabaseSchema source, DatabaseSchema target)
    {
        var result = new List<SchemaDifference>();
        CompareTables(source, target, result); CompareIndexes(source, target, result); CompareModules(source, target, result); return result;
    }
    static void CompareTables(DatabaseSchema s, DatabaseSchema t, List<SchemaDifference> r)
    {
        var st=s.Tables.ToDictionary(x=>Key(x.Schema,x.Name),StringComparer.OrdinalIgnoreCase); var tt=t.Tables.ToDictionary(x=>Key(x.Schema,x.Name),StringComparer.OrdinalIgnoreCase);
        foreach(var x in st.Values) { if(!tt.TryGetValue(Key(x.Schema,x.Name),out var y)){r.Add(Diff(SchemaObjectType.Table,x.Schema,x.Name,DifferenceType.Added,$"Table {x.Schema}.{x.Name} exists only in source.")); continue;} CompareColumns(x,y,r); }
        foreach(var x in tt.Values.Where(x=>!st.ContainsKey(Key(x.Schema,x.Name)))) r.Add(new SchemaDifference{ObjectType=SchemaObjectType.Table,SchemaName=x.Schema,ObjectName=x.Name,DifferenceType=DifferenceType.Removed,Description="Target contains object that does not exist in Source. No DROP statement generated automatically.",IsPotentiallyDestructive=true});
    }
    static void CompareColumns(TableSchema s, TableSchema t, List<SchemaDifference> r)
    { var sc=s.Columns.ToDictionary(x=>x.Name,StringComparer.OrdinalIgnoreCase); var tc=t.Columns.ToDictionary(x=>x.Name,StringComparer.OrdinalIgnoreCase); foreach(var c in sc.Values){if(!tc.TryGetValue(c.Name,out var d)){r.Add(Diff(SchemaObjectType.Column,s.Schema,s.Name+"."+c.Name,DifferenceType.Added,$"Add {c.Name} {SqlType(c)}",Sql(c)));} else if(!Equivalent(c,d)) r.Add(Diff(SchemaObjectType.Column,s.Schema,s.Name+"."+c.Name,DifferenceType.Modified,$"Column {c.Name} differs: {SqlType(c)} vs {SqlType(d)}",Sql(c),Sql(d), c.TypeName.Equals(d.TypeName,StringComparison.OrdinalIgnoreCase)&&((c.Length??0)>=(d.Length??0))));} }
    static void CompareIndexes(DatabaseSchema s, DatabaseSchema t, List<SchemaDifference> r){var si=s.Indexes.ToDictionary(x=>Key(x.Schema,x.Table,x.Name),StringComparer.OrdinalIgnoreCase);var ti=t.Indexes.ToDictionary(x=>Key(x.Schema,x.Table,x.Name),StringComparer.OrdinalIgnoreCase);foreach(var x in si.Values){if(!ti.TryGetValue(Key(x.Schema,x.Table,x.Name),out var y)){r.Add(Diff(SchemaObjectType.Index,x.Schema,x.Name,DifferenceType.Added,$"Index {x.Name} on {x.Schema}.{x.Table} is missing.",IndexSql(x)));}else if(!Equals(x,y))r.Add(Diff(SchemaObjectType.Index,x.Schema,x.Name,DifferenceType.Modified,$"Index {x.Name} differs.",IndexSql(x),IndexSql(y),true));}foreach(var x in ti.Values.Where(x=>!si.ContainsKey(Key(x.Schema,x.Table,x.Name))))r.Add(new SchemaDifference{ObjectType=SchemaObjectType.Index,SchemaName=x.Schema,ObjectName=x.Name,DifferenceType=DifferenceType.Removed,Description="Target contains index not present in source; no DROP generated.",IsPotentiallyDestructive=true});}
    static void CompareModules(DatabaseSchema s, DatabaseSchema t, List<SchemaDifference> r){var sm=s.Modules.ToDictionary(x=>Key(x.Schema,x.Name,x.ObjectType),StringComparer.OrdinalIgnoreCase);var tm=t.Modules.ToDictionary(x=>Key(x.Schema,x.Name,x.ObjectType),StringComparer.OrdinalIgnoreCase);foreach(var x in sm.Values){if(!tm.TryGetValue(Key(x.Schema,x.Name,x.ObjectType),out var y))r.Add(Diff(x.ObjectType,x.Schema,x.Name,DifferenceType.Added,"Module exists only in source.",x.Definition));else if(!Normalize(x.Definition).Equals(Normalize(y.Definition),StringComparison.OrdinalIgnoreCase))r.Add(Diff(x.ObjectType,x.Schema,x.Name,DifferenceType.Modified,"Definition changed.",x.Definition,y.Definition));}foreach(var x in tm.Values.Where(x=>!sm.ContainsKey(Key(x.Schema,x.Name,x.ObjectType))))r.Add(new SchemaDifference{ObjectType=x.ObjectType,SchemaName=x.Schema,ObjectName=x.Name,DifferenceType=DifferenceType.Removed,Description="Target contains module not present in source; no DROP generated.",TargetDefinition=x.Definition,IsPotentiallyDestructive=true});}
    static SchemaDifference Diff(SchemaObjectType o,string s,string n,DifferenceType d,string desc,string? src=null,string? tar=null,bool safe=false)=>new(){ObjectType=o,SchemaName=s,ObjectName=n,DifferenceType=d,Description=desc,SourceDefinition=src,TargetDefinition=tar,IsPotentiallyDestructive=d==DifferenceType.Removed&&!safe};
    static string Key(params object[] p)=>string.Join(".",p); static string Normalize(string x)=>string.Join(" ",x.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries)); static bool Equivalent(ColumnSchema a,ColumnSchema b)=>string.Equals(SqlType(a),SqlType(b),StringComparison.OrdinalIgnoreCase)&&a.IsNullable==b.IsNullable&&a.IsIdentity==b.IsIdentity&&string.Equals(a.DefaultDefinition,b.DefaultDefinition,StringComparison.OrdinalIgnoreCase); static string Sql(ColumnSchema c)=>$"{SqlType(c)} {(c.IsNullable?"NULL":"NOT NULL")}"; static string SqlType(ColumnSchema c)=>c.TypeName.ToLowerInvariant() switch {"nvarchar" or "nchar" => $"{c.TypeName.ToUpperInvariant()}({(c.Length<0?"MAX":c.Length?.ToString()??"" )})", "varchar" or "char" or "varbinary" => $"{c.TypeName.ToUpperInvariant()}({(c.Length<0?"MAX":c.Length?.ToString()??"")})", "decimal" or "numeric"=>$"{c.TypeName.ToUpperInvariant()}({c.Precision},{c.Scale})",_=>c.TypeName.ToUpperInvariant()}; static bool Equals(IndexSchema a,IndexSchema b)=>a.IsUnique==b.IsUnique&&a.IsClustered==b.IsClustered&&a.Columns.SequenceEqual(b.Columns,StringComparer.OrdinalIgnoreCase)&&a.IncludedColumns.SequenceEqual(b.IncludedColumns,StringComparer.OrdinalIgnoreCase)&&string.Equals(a.FilterDefinition,b.FilterDefinition,StringComparison.OrdinalIgnoreCase); static string IndexSql(IndexSchema i)=>$"{i.Name} ON [{i.Schema}].[{i.Table}] ({string.Join(", ",i.Columns.Select(x=>$"[{x}]"))})";
}
